### ISSUE TITLE
[Question] Origin of the ARM COFF/PE support code

### ISSUE THREAD

**Issue by dogtopus** [MaxKellermann/cegcc-build#8]
Not really an issue but: I was working on a custom ARM PE target (neither CE nor ARM NT) for GCC. Unlike this project, I started by porting over the i386 PE support to ARM. During the process, I noticed that the more I debug, the more it starts to look like the ARM PE support code hosted here. So I'm curious: is this really ported from the legacy CeGCC 4 (as you stated on your blog) or did you started from i386 PE support and bent it to support ARM?

**Comment by MaxKellermann** [comment]
I'm not the author - I only did lots of fixups after the fact, to port these patches to newer GCC versions, because I did an open source project and I wanted to switch to C++11 (>10 years ago, of course). Most of this is from the cegcc/mingw32ce project which has been defunct for many years. I don't know its exact origin.

**Comment by dogtopus** [comment]
Hm so I guess the original CeGCC project author probably did the exact same thing as me, but with GCC 4 instead. It only looked similar probably because the CygMinG support code didn't change too much during all those years.
